### ISSUE TITLE
Use functions instead of callable classes in the docs

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#113]
I am not sure what to do. And I am open to any suggestions about it. 
What do you want to see?

**Comment by michaelbukachi** [comment]
Hello, perhaps you can call examples for invocation:
An example:
```
def hello():
    return 'hi'
```
The above function is easy to understand since it's standard syntax.
```
class Hello(object):
    def __call__(self):
         return 'hi'
```
The above syntax is a bit more difficult to understand. It's not easy for someone who has not used Python for a long time to know that the above code is invoked the following:
```
hello = Hello()
hello() # call function
```

**Comment by sobolevn** [comment]
Oh, I see. That's a good idea.
