### ISSUE TITLE
Add a helper function for unify

### ISSUE THREAD

**Issue by SaschaSchlemmer** [dry-python/returns#283]
Apparently the folks that develop mypy have fixed an issue with generics so that now `unify` may be typed properly

```python

A = TypeVar('A')
B = TypeVar('B')
F1 = TypeVar('F1')
F2 = TypeVar('F2')

def unify(f: Callable[[A], Result[B, F2]]) -> Callable[[Result[A, F1]], Result[B, Union[F1, F2]]]:
    return lambda x: x.unify(f)
```

**Comment by sobolevn** [comment]
Awesome! @SaschaSchlemmer would please submit it?

**Comment by SaschaSchlemmer** [comment]
I just had a look at `pointfree.py` and noticed that for `bind` the code is actually defined in different modules `bind.py` and `bind.pyi` in __generated/pointfree_. Should I just copy those adapt the types/implementation to fit `unify`? Or is there actually some code generation?

**Comment by sobolevn** [comment]
Well, I used to generate code by a third-party script. But now I just use hands to do that.
That's what we have to pay for lack of HKT 😢

**Comment by SaschaSchlemmer** [comment]
Ah I see, so I'll basically just copy&paste from `bind` and adapt the interesting bits :)  

**Unrelated sidenote:** You may remember me asking about why `Success` and `Failure` are not proper classes and the idea for a `handle` function that removes failure cases off a `Result` a while ago. I think I have come up with a solution (that does not require a plugin or any other hacks) but does require quite some Refactoring of `Result`/`Success` and `Failure`. Can I maybe send you a gist with my code?

**Comment by sobolevn** [comment]
@SaschaSchlemmer sure thing!

**Comment by SaschaSchlemmer** [comment]
https://gist.github.com/SaschaSchlemmer/ed4489332e5f90e411193b6af361e1db

**Comment by sobolevn** [comment]
@astynax can you please take a look at it?

**Comment by SaschaSchlemmer** [comment]
@sobolevn Have you had the chance to look at and play the with code in the gist?

**Comment by sobolevn** [comment]
Sorry, not really. I will give you my feedback when I have the time.

**Comment by sobolevn** [comment]
Thanks a lot (and sorry) for the long way, @SaschaSchlemmer!

You have made a great sample and provided awesome examples. 👍 

The thing with your solution is that people might and will use `Success[X]` and `Failure[Y]` as separate types. And I want to stop them from doing it. Why? Because there's no such thing as just `Success` or just `Failure`. One does not make any sense without the second. That's why one must use `Result` that represents both these states.

So, current solution allows us to hide implementation details like `_Success` and `_Failure` classes that should not be used (leading `_` tells that this thing is protected). And we have public type constructors: `Success` and `Failure` that technically cannot be used as types.

And I would love it to stay this way. I hope my decision is reasonable and clear. I would love to hear your feedback.
