### ISSUE TITLE
Consider adding `flat_map` pointfree helper

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#421]
It works like so: `flat_map(function)(container) == flatten(map(function)(container))`

**Comment by thepabloaguilar** [comment]
What is the purpose of this helper?
I'm asking that because `flatten` merge nested containers, if you execute:
```python
map_(function)(container)
```
You won't have a nested container, just the same container with a new value. If you apply `flatten` to the result you'll just unwrap the container value (if it is success type)!

Unless that you use a function that returns a `Result`, like:
```python
def function(argument: Any) -> Result[Any, Any]:
    return Success(argument)
```
But if you use that function on `map_` doesn't make some sense because `map_` is to work with pure functions and `Result` is a *"side effect"* (I don't remember if it's the right word)!

I'm questioning because I really want to understand more about the functional programming way.

**Comment by jjmalina** [comment]
I think this could be useful when you want to take the left value of a container and use it and return a new container which can then be taken further.

Scala has [flatMap defined](https://www.scala-lang.org/api/current/scala/Option.html#flatMap[B](f:A=%3EOption[B]):Option[B]) on `Option` as `def flatMap[B](f: (A) => Option[B]): Option[B]`. The signatures of flatMap on `[Try](https://www.scala-lang.org/api/current/scala/util/Try.html#flatMap[U](f:T=%3Escala.util.Try[U]):scala.util.Try[U])` and `[Either](https://www.scala-lang.org/api/current/scala/util/Either.html)` are similar. So I think these would correspond to `Maybe`, and `Result`.

If we did the same then it could work like this:
```python
from typing import Optional, Tuple
from returns.maybe import Some, maybe

SPECIAL_CHARS = iter('!@#$%^&*()?><:"{}+_,./;[]=-`~')

@maybe
def validate_password_length(pw: str) -> Optional[str]:
    if len(pw) < 8:
        return None
    return pw


@maybe
def validate_password_chars(pw: str) -> Optional[Tuple[str, int]]:
    chars_in_pw = len([c for c in SPECIAL_CHARS if c in pw])
    if not chars_in_pw:
        return None
    return (pw, chars_in_pw)

assert Some('password!').flat_map(validate_password_length).flat_map(validate_password_chars) == Some(('password!', 1))
```
but you could just write the same with bind:
```python
assert Some('password!').bind(validate_password_length).bind(validate_password_chars) == Some(('password!', 1))
```
So is `flat_map` not just the same as `bind`? What am I missing?
The other issue I have with bind is that both the right have the same value but fail the equality check.

**Comment by thepabloaguilar** [comment]
> Why not just have a `flat_map` helper/method which uses bind underneath?

It's a helper function for `MappableN` classes only, they just have the `map` method. So `flat_map` can be useful in this case!

**Comment by sobolevn** [comment]
Going to close this as won't fix. I don't see any advantage over our current `map` / `bind`.
