### ISSUE TITLE
Consider adding execution flow tracking mechanism for debugging 

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#45]
We can add a special value that will track the execution of the following snippet:

```python
tracked: Tracked[int]

Success(tracked)
   .map(lambda x: x * 2)
   .fix(lambda x: -x)
   .bind(lambda x: Success(x) if x > 10 else Failure(x))
   .fix(lambda x: abs(x))
```

It is hard to tell from the start. But, we can use `Writer` monad for that. And it will allow us to build nice tracebacks.

We can sync the format with the one stories output. I would say that `json` is the best option for the output.

**Comment by proofit404** [comment]
One of the reasons `stories` library build on top of DSL is the ability to collect such data at the definition time.

Also, these plugins are transparent to the end user. You can use one, all or none of them and not a single line of your project code base will change.

With so-called "special values" you forcing situations like 
- Oh my, I can't understand how to reproduce this error from Sentry
- I should rewrite part of my project to include this information to the same error in the future
- I can't do it, because of other code parts. They also rely on this part.
- Also, I can't do it because I don't have time to refactor this part.

This feature became useless pretty quick.

**Comment by sobolevn** [comment]
Yeap, moreover I prefer to write pure things. And I expect my monads to be pure.
Not to track the execution, build logs, etc.

This is 100% out of scope.

I should concentrate on providing `Reader`, `State`, and `Writer` monads. 
Using these primitives users can do whatever they want with their execution flow.

**Comment by sobolevn** [comment]
That's what I am talking about:

```haskell
import Data.Monoid
import Data.Foldable
import Control.Monad.Writer
import Control.Monad.State

fact1 :: Integer -> Writer String Integer
fact1 0 = return 1
fact1 n = do
  let n' = n-1
  tell $ "We've taken one away from " ++ show n ++ "\n"
  m <- fact1 n'
  tell $ "We've called f " ++ show m ++ "\n"
  let r = n * m
  tell $ "We've multiplied " ++ show n
                  ++ " and " ++ show m ++ "\n"
  return r
```

http://fprog.ru/2009/issue1/dan-piponi-haskell-monoids-and-their-uses/

**Comment by proofit404** [comment]
![](https://memegenerator.net/img/instances/65812380/this-is-how-we-print-a-newline-in-haskell.jpg)
