### ISSUE TITLE
`is_successful` should accepts `ResultLikeN`

### ISSUE THREAD

**Issue by thepabloaguilar** [dry-python/returns#536]
`is_successful` accepts only `Unwrappable` types, but this is not semantic at all.
Now, the big difference between `ResultLikeN` and `ResultBasedN` is that we can unwrap the second one but we have to be able to use `is_successful` with `ResultLikeN` because it represents computation paths (success, failure) too.

And I think this is not a great function name to use with `Maybe`, `is_empty` and `is_nothing` are better names and can be a separated function! Essentially `Maybe` tells us if we have something or not.

**Comment by sobolevn** [comment]
My understanding of `ResultLikeN` / `ResultBasedN` is that `ResultLikeN` is not a real result. For example `ReaderResult` is a part of `ResultLikeN` interface, but it cannot be used with `is_successful`, why? 

Because there's no `Result` yet! We need to provide `deps` to the context first.

That's is exactly why these types cannot be unwrapped. There's nothing to unwrap yet. The same goes for `FutureResult`. Since we need to `await` it first.

**Comment by thepabloaguilar** [comment]
Oh, I got your full point now, thanks!! I'll improve the documentation section asap, we already have the section but with no content:

[What is the difference between ResultLikeN and ResultBasedN?](https://returns.readthedocs.io/en/latest/pages/interfaces.html#what-is-the-difference-between-resultliken-and-resultbasedn)
